management:
  port: 8090
  context-path: /management

server:
  port: 8085
  context-path: /mlapi
  display-name: mlapi
  connection-timeout: 60000
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
      - application/xml
      - application/xhtml+xml
      - text/html
      - text/xml
      - text/plain
  tomcat:
    max-threads: 0
    min-spare-threads: 0
    uri-encoding: UTF-8
    remote-ip-header: X-FORWARDED-FOR

spring:
  application:
    name: mlapi

data:
    mongodb:
      host: localhost
      port: 27017
      database: metric
      repositories.enabled: true

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    ROOT: WARN
    com:
      ml: DEBUG
    org:
      springframework: INFO
      springframework.test.web.servlet.result: DEBUG
      springframework.data.mongodb.core.MongoTemplate: DEBUG
      springframework.web.filter: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


