version: '2'

services:

  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/
    volumes:
      - ./data/db:/data/db
      - ./mongo_realdata:/tmp/mongodata:ro
    ports:
       - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

  mongo-express:
    image: autopilotpattern/mongo-express
    restart: always
    mem_limit: "512m"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo
    labels:
      - triton.cns.services=mongo-express
    ports:
      - "8081:8081"

